# Generated by Django 3.0.8 on 2021-01-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0002_auto_20201116_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalAutopsySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
                ('facility', models.TextField()),
                ('cause', models.TextField()),
                ('warnings', models.TextField()),
                ('errors', models.TextField()),
                ('va_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='va_data_management.VerbalAutopsy')),
            ],
        ),
    ]
