# Generated by Django 3.1.5 on 2021-02-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0002_auto_20201116_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causecodingissue',
            name='settings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='causeofdeath',
            name='settings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='historicalcauseofdeath',
            name='settings',
            field=models.JSONField(),
        ),
    ]
