# Generated by Django 3.0.8 on 2021-01-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0003_verbalautopsysummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verbalautopsysummary',
            old_name='va_id',
            new_name='verbalautopsy',
        ),
    ]
