# Generated by Django 3.0.8 on 2021-01-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0004_auto_20210121_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbalautopsysummary',
            name='name',
        ),
    ]
