# Generated by Django 3.0.8 on 2021-01-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0005_remove_verbalautopsysummary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbalautopsysummary',
            name='verbalautopsy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='va_data_management.VerbalAutopsy'),
        ),
    ]
