# Generated by Django 3.1.5 on 2021-04-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0005_vausername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verbalautopsy",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verbalautopsies",
                to="va_data_management.location",
            ),
        ),
    ]
