# Generated by Django 3.1.5 on 2022-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0006_auto_20210430_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marks the record as deleted'),
        ),
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='duplicate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marks the record as duplicate'),
        ),
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='unique_va_identifiers_hash',
            field=models.TextField(blank=True, verbose_name='Hash of the unique_va_identifiers'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marks the record as deleted'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='duplicate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marks the record as duplicate'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='unique_va_identifiers_hash',
            field=models.TextField(blank=True, verbose_name='Hash of the unique_va_identifiers'),
        ),
    ]
