# Generated by Django 3.1.5 on 2021-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0006_auto_20210430_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.PositiveSmallIntegerField(choices=[(1, 'Import'), (2, 'Coding')])),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('verbal_autopsies', models.ManyToManyField(to='va_data_management.VerbalAutopsy')),
            ],
            options={'ordering': ['-date_started']},
        ),
    ]
