# Generated by Django 3.0.8 on 2021-01-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0006_auto_20210121_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerbalAutopsySummary',
        ),
    ]
