# Generated by Django 3.1.5 on 2022-01-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0007_auto_20210302_1943"),
        ("va_data_management", "0007_auto_20210602_1509"),
    ]

    operations = []
