# Generated by Django 3.1.5 on 2022-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0008_merge_20220105_2201"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="cod_codes_dhis",
            new_name="CODCodesDHIS",
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10008_check",
            field=models.TextField(
                blank=True,
                verbose_name="It is not possible to select that the respondent is the child of the         deceased and enter that the deceased is a neonate or child. Please go         back and correct the selection.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10011",
            field=models.TextField(
                blank=True, verbose_name="Time at start of interview"
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10012",
            field=models.TextField(blank=True, verbose_name="Date of interview"),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10055",
            field=models.TextField(
                blank=True,
                verbose_name="What was her/his place of usual residence? (the place where the person         lived most of the year)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10138",
            field=models.TextField(
                blank=True,
                verbose_name="Was there any diagnosis by a health professional of Chronic         Obstructive Pulmonary Disease (COPD)?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10173",
            field=models.TextField(
                blank=True,
                verbose_name="Calculated Field: During the illness that led to death did his/her         breathing sound like any of the following:",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10173_nc",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death did his/her breathing sound like         any of the following:",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10183",
            field=models.TextField(
                blank=True,
                verbose_name="How many stools did the baby or child have on the day that loose         liquid stools were most frequent?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10201_a",
            field=models.TextField(
                blank=True,
                verbose_name="Enter how long before death (s)he had a more than usually protruding         belly (abdomen) in days:",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10201_unit",
            field=models.TextField(
                blank=True,
                verbose_name="For how long before death did (s)he have a more than usually         protruding belly (abdomen)?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10202",
            field=models.TextField(
                blank=True,
                verbose_name="Enter how long before death (s)he had a more than usually protruding         belly (abdomen) in months:",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10220",
            field=models.TextField(
                blank=True,
                verbose_name="Did (s)he experience any generalized convulsions or fits during the         illness that led to death?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10239",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death, did he/she have areas of the         skin that turned black?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10240",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death, did he/she have areas of the         skin with redness and swelling?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10245",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death, did s/he have a whitish rash         inside the mouth or on the tongue?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10310",
            field=models.TextField(
                blank=True,
                verbose_name="Please confirm, when she died, she was NEITHER pregnant NOR had delivered,         had an abortion, or miscarried within 12 months of when she died--is that right?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10310_check",
            field=models.TextField(
                blank=True,
                verbose_name='If the response is NO, DON\'T KNOW, OR REFUSED, it indicates some         uncertainty as to whether the cause of death could have been a maternal         or pregnancy-related cause. Go back to the question "Did she ever have         a period or menstruate?" and follow the process again. If it is confirmed         that the death was related to pregnancy, proceed with the next question         ‚ÄúDid she die during labour or delivery?‚Äù',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10327",
            field=models.TextField(
                blank=True,
                verbose_name="Was there vaginal bleeding during the last 3 months of pregnancy but         before labour started?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10334",
            field=models.TextField(
                blank=True,
                verbose_name="Did she recently have a pregnancy that ended in an abortion         (spontaneous or induced)?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10368",
            field=models.TextField(
                blank=True,
                verbose_name="Were there any complications in the late part of the pregnancy         (defined as the last 3 months, before labour)?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10370",
            field=models.TextField(
                blank=True,
                verbose_name="Was any part of the baby physically abnormal at time of delivery?         (for example: body part too large or too small, additional growth on body)?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10391",
            field=models.TextField(
                blank=True,
                verbose_name="Did you/the mother receive any vaccinations since reaching adulthood         including during this pregnancy?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10396",
            field=models.TextField(
                blank=True,
                verbose_name="During the last 3 months of pregnancy, labour or delivery, did         you/the baby's mother suffer from high blood pressure?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10398",
            field=models.TextField(
                blank=True,
                verbose_name="Did you/the baby's mother have foul smelling vaginal discharge during         pregnancy or after delivery?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10399",
            field=models.TextField(
                blank=True,
                verbose_name="During the last 3 months of pregnancy, labour or delivery, did         you/the baby's mother suffer from convulsions?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10400",
            field=models.TextField(
                blank=True,
                verbose_name="During the last 3 months of pregnancy did you/the baby's mother         suffer from blurred vision?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10402",
            field=models.TextField(
                blank=True,
                verbose_name="Did you/the baby's mother have vaginal bleeding during the last 3         months of pregnancy but before labour started?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10434",
            field=models.TextField(
                blank=True,
                verbose_name="What was the name and address of any hospital, health center or         clinic where care was sought",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10446",
            field=models.TextField(
                blank=True,
                verbose_name="Has the deceased's (biological) mother ever been told she had         HIV/AIDS by a health worker?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10451",
            field=models.TextField(
                blank=True,
                verbose_name="Did (s)he use motorized transport to get to the hospital or health facility?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10453",
            field=models.TextField(
                blank=True,
                verbose_name="Were there any problems with the way (s)he was treated (medical treatment,         procedures, interpersonal attitudes, respect, dignity) in the hospital or health facility?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10454",
            field=models.TextField(
                blank=True,
                verbose_name="Were there any problems getting medications or diagnostic tests in         the hospital or health facility?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10455",
            field=models.TextField(
                blank=True,
                verbose_name="Does it take more than 2 hours to get to the nearest hospital or         health facility from the deceased's household?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10456",
            field=models.TextField(
                blank=True,
                verbose_name="In the final days before death, were there any doubts about whether         medical care was needed?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10458",
            field=models.TextField(
                blank=True,
                verbose_name="In the final days before death, did anyone use a telephone or cell         phone to call for help?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10459",
            field=models.TextField(
                blank=True,
                verbose_name="Over the course of illness, did the total costs of care and treatment         prohibit other household payments?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10476",
            field=models.TextField(
                blank=True,
                verbose_name="Thank you for your information. Now can you please tell me in your own         words about the events that led to the death?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10235_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Doesn\'t Know" or "Refused to answer"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10260_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "only one side paralysed" and "left and         right side" or "whole body" together. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10260_check2",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Doesn\'t Know" or "Refused to answer"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id1036X_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "No usual size at Birth", "No weighing         under 2.5 kg" and "No weighing over 4.5 kg" together. Please go back         and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10389_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "No" to all three previous questions.         Please go back and review the answers.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10414_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select cigarettes or pipe and "no" to         "Did (s)he smoke tobacco?". Please go back and correct the selections.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10431_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "No vaccines", "Don\'t know" or "refuse"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10433_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "refuse" together with         other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10477_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "None of the above"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10478_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "None of the above"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10479_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "None of the above"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10008_check",
            field=models.TextField(
                blank=True,
                verbose_name="It is not possible to select that the respondent is the child of the         deceased and enter that the deceased is a neonate or child. Please go         back and correct the selection.",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10011",
            field=models.TextField(
                blank=True, verbose_name="Time at start of interview"
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10012",
            field=models.TextField(blank=True, verbose_name="Date of interview"),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10055",
            field=models.TextField(
                blank=True,
                verbose_name="What was her/his place of usual residence? (the place where the person         lived most of the year)",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10138",
            field=models.TextField(
                blank=True,
                verbose_name="Was there any diagnosis by a health professional of Chronic         Obstructive Pulmonary Disease (COPD)?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10173",
            field=models.TextField(
                blank=True,
                verbose_name="Calculated Field: During the illness that led to death did his/her         breathing sound like any of the following:",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10173_nc",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death did his/her breathing sound like         any of the following:",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10183",
            field=models.TextField(
                blank=True,
                verbose_name="How many stools did the baby or child have on the day that loose         liquid stools were most frequent?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10201_a",
            field=models.TextField(
                blank=True,
                verbose_name="Enter how long before death (s)he had a more than usually protruding         belly (abdomen) in days:",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10201_unit",
            field=models.TextField(
                blank=True,
                verbose_name="For how long before death did (s)he have a more than usually         protruding belly (abdomen)?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10202",
            field=models.TextField(
                blank=True,
                verbose_name="Enter how long before death (s)he had a more than usually protruding         belly (abdomen) in months:",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10220",
            field=models.TextField(
                blank=True,
                verbose_name="Did (s)he experience any generalized convulsions or fits during the         illness that led to death?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10239",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death, did he/she have areas of the         skin that turned black?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10240",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death, did he/she have areas of the         skin with redness and swelling?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10245",
            field=models.TextField(
                blank=True,
                verbose_name="During the illness that led to death, did s/he have a whitish rash         inside the mouth or on the tongue?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10310",
            field=models.TextField(
                blank=True,
                verbose_name="Please confirm, when she died, she was NEITHER pregnant NOR had delivered,         had an abortion, or miscarried within 12 months of when she died--is that right?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10310_check",
            field=models.TextField(
                blank=True,
                verbose_name='If the response is NO, DON\'T KNOW, OR REFUSED, it indicates some         uncertainty as to whether the cause of death could have been a maternal         or pregnancy-related cause. Go back to the question "Did she ever have         a period or menstruate?" and follow the process again. If it is confirmed         that the death was related to pregnancy, proceed with the next question         ‚ÄúDid she die during labour or delivery?‚Äù',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10327",
            field=models.TextField(
                blank=True,
                verbose_name="Was there vaginal bleeding during the last 3 months of pregnancy but         before labour started?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10334",
            field=models.TextField(
                blank=True,
                verbose_name="Did she recently have a pregnancy that ended in an abortion         (spontaneous or induced)?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10368",
            field=models.TextField(
                blank=True,
                verbose_name="Were there any complications in the late part of the pregnancy         (defined as the last 3 months, before labour)?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10370",
            field=models.TextField(
                blank=True,
                verbose_name="Was any part of the baby physically abnormal at time of delivery?         (for example: body part too large or too small, additional growth on body)?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10391",
            field=models.TextField(
                blank=True,
                verbose_name="Did you/the mother receive any vaccinations since reaching adulthood         including during this pregnancy?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10396",
            field=models.TextField(
                blank=True,
                verbose_name="During the last 3 months of pregnancy, labour or delivery, did         you/the baby's mother suffer from high blood pressure?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10398",
            field=models.TextField(
                blank=True,
                verbose_name="Did you/the baby's mother have foul smelling vaginal discharge during         pregnancy or after delivery?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10399",
            field=models.TextField(
                blank=True,
                verbose_name="During the last 3 months of pregnancy, labour or delivery, did         you/the baby's mother suffer from convulsions?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10400",
            field=models.TextField(
                blank=True,
                verbose_name="During the last 3 months of pregnancy did you/the baby's mother         suffer from blurred vision?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10402",
            field=models.TextField(
                blank=True,
                verbose_name="Did you/the baby's mother have vaginal bleeding during the last 3         months of pregnancy but before labour started?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10434",
            field=models.TextField(
                blank=True,
                verbose_name="What was the name and address of any hospital, health center or         clinic where care was sought",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10446",
            field=models.TextField(
                blank=True,
                verbose_name="Has the deceased's (biological) mother ever been told she had         HIV/AIDS by a health worker?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10451",
            field=models.TextField(
                blank=True,
                verbose_name="Did (s)he use motorized transport to get to the hospital or health facility?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10453",
            field=models.TextField(
                blank=True,
                verbose_name="Were there any problems with the way (s)he was treated (medical treatment,         procedures, interpersonal attitudes, respect, dignity) in the hospital or health facility?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10454",
            field=models.TextField(
                blank=True,
                verbose_name="Were there any problems getting medications or diagnostic tests in         the hospital or health facility?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10455",
            field=models.TextField(
                blank=True,
                verbose_name="Does it take more than 2 hours to get to the nearest hospital or         health facility from the deceased's household?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10456",
            field=models.TextField(
                blank=True,
                verbose_name="In the final days before death, were there any doubts about whether         medical care was needed?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10458",
            field=models.TextField(
                blank=True,
                verbose_name="In the final days before death, did anyone use a telephone or cell         phone to call for help?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10459",
            field=models.TextField(
                blank=True,
                verbose_name="Over the course of illness, did the total costs of care and treatment         prohibit other household payments?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10476",
            field=models.TextField(
                blank=True,
                verbose_name="Thank you for your information. Now can you please tell me in your own         words about the events that led to the death?",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10235_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Doesn\'t Know" or "Refused to answer"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10260_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "only one side paralysed" and "left and         right side" or "whole body" together. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10260_check2",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Doesn\'t Know" or "Refused to answer"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id1036X_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "No usual size at Birth", "No weighing         under 2.5 kg" and "No weighing over 4.5 kg" together. Please go back         and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10389_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "No" to all three previous questions.         Please go back and review the answers.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10414_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select cigarettes or pipe and "no" to         "Did (s)he smoke tobacco?". Please go back and correct the selections.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10431_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "No vaccines", "Don\'t know" or "refuse"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10433_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "refuse" together with         other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10477_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "None of the above"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10478_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "None of the above"         together with other options. Please go back and correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10479_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t know" or "None of the above"         together with other options. Please go back and correct the selection.',
            ),
        ),
    ]
