# Generated by Django 3.1.5 on 2022-02-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0008_merge_20220105_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verbalautopsy',
            options={'permissions': (('bulk_delete', 'Can bulk delete'),)},
        ),
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='duplicate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marks the record as duplicate'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='unique_va_identifier',
            field=models.TextField(blank=True, verbose_name='md5 hash of the unique_va_identifiers'),
        ),
        migrations.AlterField(
            model_name='historicalverbalautopsy',
            name='Id10011',
            field=models.TextField(blank=True, verbose_name='Time at start of interview'),
        ),
        migrations.AlterField(
            model_name='historicalverbalautopsy',
            name='Id10012',
            field=models.TextField(blank=True, verbose_name='Date of interview'),
        ),
        migrations.AlterField(
            model_name='verbalautopsy',
            name='Id10011',
            field=models.TextField(blank=True, verbose_name='Time at start of interview'),
        ),
        migrations.AlterField(
            model_name='verbalautopsy',
            name='Id10012',
            field=models.TextField(blank=True, verbose_name='Date of interview'),
        ),
        migrations.AddIndex(
            model_name='verbalautopsy',
            index=models.Index(fields=['unique_va_identifier'], name='va_data_man_unique__8f25af_idx'),
        ),
    ]
