# Generated by Django 3.1.5 on 2022-02-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0009_auto_20220218_1457"),
        ("va_data_management", "0010_auto_20220212_1800"),
    ]

    operations = []
