# Generated by Django 3.1.5 on 2022-02-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0011_merge_20220225_1939'),
        ('va_data_management', '0007_codingbatch_importbatch'),
    ]

    operations = [
    ]
