# Generated by Django 3.1.5 on 2022-02-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0011_merge_20220225_1939'),
        ('va_data_management', '0009_auto_20220203_1624'),
    ]

    operations = [
    ]
