# Generated by Django 3.1.5 on 2022-03-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0012_merge_20220228_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='version',
            field=models.TextField(blank=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='version',
            field=models.TextField(blank=True, verbose_name='Version'),
        ),
    ]
