# Generated by Django 3.1.5 on 2022-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0012_merge_20220311_1959"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10366_a",
            field=models.TextField(
                blank=True,
                verbose_name="What was the weight of the deceased at         birth? [Enter weight in grammes:]",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10366_b",
            field=models.TextField(
                blank=True,
                verbose_name="What was the weight of the deceased at birth?         [Enter weight in kilograms:]",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="Id10366_unit",
            field=models.TextField(
                blank=True,
                verbose_name="What was the weight of the deceased at         birth? [Enter weight in:]",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="id10173_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t         know" or "refuse" together with other options. Please go back and         correct the selection.',
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10366_a",
            field=models.TextField(
                blank=True,
                verbose_name="What was the weight of the deceased at         birth? [Enter weight in grammes:]",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10366_b",
            field=models.TextField(
                blank=True,
                verbose_name="What was the weight of the deceased at birth?         [Enter weight in kilograms:]",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="Id10366_unit",
            field=models.TextField(
                blank=True,
                verbose_name="What was the weight of the deceased at         birth? [Enter weight in:]",
            ),
        ),
        migrations.AlterField(
            model_name="verbalautopsy",
            name="id10173_check",
            field=models.TextField(
                blank=True,
                verbose_name='It is not possible to select "Don\'t         know" or "refuse" together with other options. Please go back and         correct the selection.',
            ),
        ),
    ]
