# Generated by Django 3.1.5 on 2022-03-29 19:01

from django.db import migrations


def apply_formatting(field):
    field = ",".join(map(str, field))
    field = field.strip("[]")
    field = field.replace("'", "")
    # Convert to comma-separated if space-separated
    if "," not in field:
        field = ",".join(response for response in field.split())

    return field


def clean_multi_select_fields(apps, schema_editor):
    VerbalAutopsy = apps.get_model("va_data_management", "VerbalAutopsy")

    for va in VerbalAutopsy.objects.all():
        va.Id10173_nc = apply_formatting(va.Id10173_nc)
        va.Id10235 = apply_formatting(va.Id10235)
        va.Id10260 = apply_formatting(va.Id10260)
        va.Id10431 = apply_formatting(va.Id10431)
        va.Id10433 = apply_formatting(va.Id10433)
        va.Id10477 = apply_formatting(va.Id10477)
        va.Id10478 = apply_formatting(va.Id10478)
        va.Id10479 = apply_formatting(va.Id10479)
        va.save()


class Migration(migrations.Migration):
    dependencies = [
        ("va_data_management", "0014_auto_20220330_1128"),
    ]
    operations = [
        migrations.RunPython(clean_multi_select_fields, migrations.RunPython.noop)
    ]
