# Generated by Django 3.1.5 on 2022-07-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0015_auto_20220330_1128"),
        ("va_data_management", "0013_auto_20220225_2057"),
    ]

    operations = []
