# Generated by Django 4.1.2 on 2022-10-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0016_alter_historicalcauseofdeath_options_and_more"),
        ("va_data_management", "0016_merge_20220704_0133"),
    ]

    operations = []
