# Generated by Django 4.0.6 on 2022-12-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0016_alter_historicalcauseofdeath_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcauseofdeath",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical cause of death",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalverbalautopsy",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical verbal autopsy",
            },
        ),
        migrations.AlterField(
            model_name="historicalcauseofdeath",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalverbalautopsy",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="verbalautopsy",
            index=models.Index(fields=["Id10023"], name="death_date_filter_idx"),
        ),
    ]
