# Generated by Django 4.1.2 on 2022-11-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0016_alter_historicalcauseofdeath_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="Id10482",
            field=models.TextField(
                blank=True,
                verbose_name="Was there any diagnosis by a health professional of COVID-19?",
            ),
        ),
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="Id10483",
            field=models.TextField(
                blank=True,
                verbose_name="Did s(h)e have a recent test by a health professional for COVID-19?",
            ),
        ),
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="Id10484",
            field=models.TextField(blank=True, verbose_name="What was the result?"),
        ),
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="Id10485",
            field=models.TextField(
                blank=True, verbose_name="Did (s)he suffer from extreme fatigue?"
            ),
        ),
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="Id10486",
            field=models.TextField(
                blank=True,
                verbose_name="Did (s)he experience a new loss, change or decreased sense of smell or taste?",
            ),
        ),
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="Id10487",
            field=models.TextField(
                blank=True,
                verbose_name="In the two weeks before death, did (s)he live with, visit, or care for someone who had any COVID-19 symptoms or a positive COVID-19 test?",
            ),
        ),
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="Id10488",
            field=models.TextField(
                blank=True,
                verbose_name="In the two weeks before death, did (s)he travel to an area where COVID-19 is known to be present?",
            ),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="Id10482",
            field=models.TextField(
                blank=True,
                verbose_name="Was there any diagnosis by a health professional of COVID-19?",
            ),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="Id10483",
            field=models.TextField(
                blank=True,
                verbose_name="Did s(h)e have a recent test by a health professional for COVID-19?",
            ),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="Id10484",
            field=models.TextField(blank=True, verbose_name="What was the result?"),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="Id10485",
            field=models.TextField(
                blank=True, verbose_name="Did (s)he suffer from extreme fatigue?"
            ),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="Id10486",
            field=models.TextField(
                blank=True,
                verbose_name="Did (s)he experience a new loss, change or decreased sense of smell or taste?",
            ),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="Id10487",
            field=models.TextField(
                blank=True,
                verbose_name="In the two weeks before death, did (s)he live with, visit, or care for someone who had any COVID-19 symptoms or a positive COVID-19 test?",
            ),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="Id10488",
            field=models.TextField(
                blank=True,
                verbose_name="In the two weeks before death, did (s)he travel to an area where COVID-19 is known to be present?",
            ),
        ),
    ]
