# Generated by Django 4.1.2 on 2023-01-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0017_historicalverbalautopsy_id10482_and_more"),
        ("va_data_management", "0018_alter_historicalcauseofdeath_options_and_more"),
    ]

    operations = []
