# Generated by Django 4.1.2 on 2023-01-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0017_merge_20221031_2122"),
        ("va_data_management", "0019_merge_20230104_2001"),
    ]

    operations = []
