# Generated by Django 4.1.2 on 2023-02-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0019_merge_20230104_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalverbalautopsy',
            name='username',
        ),
        migrations.RemoveField(
            model_name='verbalautopsy',
            name='username',
        ),
        migrations.DeleteModel(
            name='VaUsername',
        ),
    ]
