# Generated by Django 4.1.2 on 2023-06-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("va_data_management", "0021_historicalverbalautopsy_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverbalautopsy",
            name="instancename",
            field=models.TextField(
                blank=True, editable=False, verbose_name="Instance Name"
            ),
        ),
        migrations.AddField(
            model_name="verbalautopsy",
            name="instancename",
            field=models.TextField(
                blank=True, editable=False, verbose_name="Instance Name"
            ),
        ),
    ]
