# Generated by Django 4.1.2 on 2024-02-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('va_data_management', '0022_historicalverbalautopsy_instancename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='path_string',
            field=models.TextField(null=True, unique=True),
        ),
    ]
