# Generated by Django 3.1.5 on 2021-04-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboard",
            options={
                "default_permissions": ("view",),
                "managed": False,
                "permissions": (
                    ("download_data", "Can download data"),
                    ("view_pii", "Can view PII in data"),
                ),
            },
        ),
    ]
