# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.292
  hooks:
    - id: ruff
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
    - id: black
