from django.db import models
from simple_history.models import HistoricalRecords
from django.db.models import JSONField
from django.contrib.auth.models import User
from treebeard.mp_tree import MP_Node
from va_explorer.va_data_management.model_choices import AgeGroup, YesNoSimilar

class Location(MP_Node):
    # Locations are set up as a tree structure, allowing a regions and sub-regions along with the
    # ability to constrain access control by region; we use django-treabeard's materialized path
    # implementation for efficiency of tree operations
    name = models.TextField()
    location_type = models.TextField()
    node_order_by = ['name']

    # A user can have their access scoped by one or more locations
    #users = models.ManyToManyField(get_user_model(), related_name='locations')

    # Automatically set timestamps
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_descendant_ids(self):
        return [descendant.id for descendant in self.get_descendants()]

    def parent_id(self):
        return self.get_parent().id

class VerbalAutopsy(models.Model):
    # Each VerbalAutopsy is associated with a facility, which is the leaf node location
    location = models.ForeignKey(Location, related_name='verbalautopsies', on_delete=models.CASCADE)

    # The VA fields collected as part of the WHO VA form or local versions
    # TODO: Need an approach that supports different variants in different countries
    deviceid = models.CharField("Device ID", blank=True, max_length=255)
    instanceid = models.CharField("Instance ID", blank=True, max_length=255)
    phonenumber = models.CharField("Phone Number", blank=True, max_length=255)
    simserial = models.CharField("SIM Serial", blank=True, max_length=255)
    username = models.CharField("Username", blank=True, max_length=255)
    bid = models.CharField("BID", blank=True, max_length=255)
    bid2 = models.CharField("BID2", blank=True, max_length=255)
    bid_check = models.CharField("BID Check", blank=True, max_length=255)
    bid_image = models.CharField("BID Image", blank=True, max_length=255)
    province = models.CharField("Province", blank=True, max_length=255)
    area = models.CharField("Area", blank=True, max_length=255)
    hospital = models.CharField("Hospital", blank=True, max_length=255)
    submissiondate = models.CharField("Submission Date", blank=True, max_length=255)
    Id10002 = models.CharField("Is this a region of high HIV/AIDS mortality?", blank=True, max_length=255)
    Id10003 = models.CharField("Is this a region of high malaria mortality?", blank=True, max_length=255)
    Id10004 = models.CharField("During which season did (s)he die?", blank=True, max_length=255)
    Id10007 = models.CharField("What is the name of VA respondent?", blank=True, max_length=255)
    Id10008 = models.CharField("What is your/the respondent's relationship to the deceased?", blank=True, max_length=255)
    Id10009 = models.CharField("Did you/the respondent live with the deceased in the period leading to her/his death?", blank=True, max_length=255)
    Id10010 = models.CharField("Name of VA interviewer", blank=True, max_length=255)
    Id10012 = models.CharField("Id10012", blank=True, max_length=255)
    Id10013 = models.CharField("Did the respondent give consent?", blank=True, max_length=255)
    Id10011 = models.CharField("Id10011", blank=True, max_length=255)
    Id10017 = models.CharField("What was the first or given name(s) of the deceased?", blank=True, max_length=255)
    Id10018 = models.CharField("What was the surname (or family name) of the deceased?", blank=True, max_length=255)
    Id10019 = models.CharField("What was the sex of the deceased?", blank=True, max_length=255)
    Id10020 = models.CharField("Is the date of birth known?", blank=True, max_length=255)
    Id10021 = models.CharField("When was the deceased born?", blank=True, max_length=255)
    Id10022 = models.CharField("Is the date of death known?", blank=True, max_length=255)
    Id10023_a = models.CharField("When did (s)he die?", blank=True, max_length=255)
    Id10023_b = models.CharField("When did (s)he die?", blank=True, max_length=255)
    Id10023 = models.CharField("Calculated Field: When did (s)he die?", blank=True, max_length=255)
    Id10024 = models.CharField("Please indicate the year of death.", blank=True, max_length=255)
    ageInDays = models.CharField("Calculated Field: ageInDays", blank=True, max_length=255)
    ageInDays2 = models.CharField("Calculated Field: ageInDays2", blank=True, max_length=255)
    ageInYears = models.CharField("Calculated Field: ageInYears", blank=True, max_length=255)
    ageInYearsRemain = models.CharField("Calculated Field: ageInYearsRemain", blank=True, max_length=255)
    ageInMonths = models.CharField("Calculated Field: ageInMonths", blank=True, max_length=255)
    ageInMonthsRemain = models.CharField("Calculated Field: ageInMonthsRemain", blank=True, max_length=255)
    isNeonatal1 = models.CharField("Calculated Field: isNeonatal1", blank=True, max_length=255)
    isChild1 = models.CharField("Calculated Field: isChild1", blank=True, max_length=255)
    isAdult1 = models.CharField("Calculated Field: isAdult1", blank=True, max_length=255)
    displayAgeNeonate = models.CharField("NEONATE was ${ageInDays} days old.", blank=True, max_length=255)
    displayAgeChild = models.CharField("CHILD was ${ageInYears} years ${ageInMonths} months and ${ageInMonthsRemain} days old.", blank=True, max_length=255)
    displayAgeAdult = models.CharField("ADULT was ${ageInYears} years old.", blank=True, max_length=255)
    age_group = models.CharField("What age group corresponds to the deceased?", blank=True, max_length=255)
    age_neonate_days = models.CharField("How many days old was the baby? [Enter neonate's age in days:]", blank=True, max_length=255)
    age_child_unit = models.CharField("How old was the child? [Enter child's age in:]", blank=True, max_length=255)
    age_child_days = models.CharField("Enter child's age in days:", blank=True, max_length=255)
    age_child_months = models.CharField("Enter child's age in months:", blank=True, max_length=255)
    age_child_years = models.CharField("Enter child's age in years:", blank=True, max_length=255)
    age_adult = models.CharField("Enter adult's age in years:", blank=True, max_length=255)
    ageInMonthsByYear = models.CharField("Calculated Field: ageInMonthsByYear", blank=True, max_length=255)
    ageInYears2 = models.CharField("Calculated Field: ageInYears2", blank=True, max_length=255)
    isNeonatal2 = models.CharField("Calculated Field: isNeonatal2", blank=True, max_length=255)
    isChild2 = models.CharField("Calculated Field: isChild2", blank=True, max_length=255)
    isAdult2 = models.CharField("Calculated Field: isAdult2", blank=True, max_length=255)
    isNeonatal = models.CharField("Calculated Field: isNeonatal", blank=True, max_length=255)
    isChild = models.CharField("Calculated Field: isChild", blank=True, max_length=255)
    isAdult = models.CharField("Calculated Field: isAdult", blank=True, max_length=255)
    ageInDaysNeonate = models.CharField("Calculated Field: ageInDaysNeonate", blank=True, max_length=255)
    Id10008_check = models.CharField("It is not possible to select that the respondent is the child of the deceased and enter that the deceased is a neonate or child. Please go back and correct the selection.", blank=True, max_length=255)
    Id10058 = models.CharField("Where did the deceased die?", blank=True, max_length=255)
    Id10051 = models.CharField("Is there a need to collect additional demographic data on the deceased?", blank=True, max_length=255)
    Id10052 = models.CharField("What was her/his citizenship/nationality?", blank=True, max_length=255)
    Id10053 = models.CharField("What was her/his ethnicity?", blank=True, max_length=255)
    Id10054 = models.CharField("What was her/his place of birth?", blank=True, max_length=255)
    Id10055 = models.CharField("What was her/his place of usual residence? (the place where the person lived most of the year)", blank=True, max_length=255)
    Id10057 = models.CharField("Where did the death occur? (specify country, province, district, village)", blank=True, max_length=255)
    Id10059 = models.CharField("What was her/his marital status?", blank=True, max_length=255)
    Id10060_check = models.CharField("Is the date of marriage available?", blank=True, max_length=255)
    Id10060 = models.CharField("What was the date of marriage?", blank=True, max_length=255)
    Id10061 = models.CharField("What was the name of the father?", blank=True, max_length=255)
    Id10062 = models.CharField("What was the name of the mother?", blank=True, max_length=255)
    Id10063 = models.CharField("What was her/his highest level of schooling?", blank=True, max_length=255)
    Id10064 = models.CharField("Was (s)he able to read and/or write?", blank=True, max_length=255)
    Id10065 = models.CharField("What was her/his economic activity status in year prior to death?", blank=True, max_length=255)
    Id10066 = models.CharField("What was her/his occupation, that is, what kind of work did (s)he mainly do?", blank=True, max_length=255)
    Id10069 = models.CharField("Is there a need to collect civil registration numbers on the deceased?", blank=True, max_length=255)
    Id10069_a = models.CharField("Do you have a Death Certificate from the Civil Registry?", blank=True, max_length=255)
    Id10070 = models.CharField("Death registration number/certificate", blank=True, max_length=255)
    Id10071_check = models.CharField("Is the date of registration available?", blank=True, max_length=255)
    Id10071 = models.CharField("Date of registration", blank=True, max_length=255)
    Id10072 = models.CharField("Place of registration", blank=True, max_length=255)
    Id10073 = models.CharField("National identification number of deceased", blank=True, max_length=255)
    Id10476 = models.TextField("Thank you for your information. Now can you please tell me in your own words about the events that led to the death?", blank=True)
    narrat_image = models.CharField("narrat_image", blank=True, max_length=255)
    Id10477 = models.CharField("Select any of the following words that were mentioned as present in the narrative.", blank=True, max_length=255)
    Id10478 = models.CharField("Select any of the following words that were mentioned as present in the narrative.", blank=True, max_length=255)
    Id10479 = models.CharField("Select any of the following words that were mentioned as present in the narrative.", blank=True, max_length=255)
    id10477_check = models.CharField("It is not possible to select \"Don't know\" or \"None of the above\" together with other options. Please go back and correct the selection.", blank=True, max_length=255)
    id10478_check = models.CharField("It is not possible to select \"Don't know\" or \"None of the above\" together with other options. Please go back and correct the selection.", blank=True, max_length=255)
    id10479_check = models.CharField("It is not possible to select \"Don't know\" or \"None of the above\" together with other options. Please go back and correct the selection.", blank=True, max_length=255)
    Id10104 = models.CharField("Did the baby ever cry?", blank=True, max_length=255)
    Id10105 = models.CharField("Did the baby cry immediately after birth, even if only a little bit?", blank=True, max_length=255)
    Id10106 = models.CharField("How many minutes after birth did the baby first cry?", blank=True, max_length=255)
    Id10107 = models.CharField("Did the baby stop being able to cry?", blank=True, max_length=255)
    Id10108 = models.CharField("How many hours before death did the baby stop crying?", blank=True, max_length=255)
    Id10109 = models.CharField("Did the baby ever move?", blank=True, max_length=255)
    Id10110 = models.CharField("Did the baby ever breathe?", blank=True, max_length=255)
    Id10111 = models.CharField("Did the baby breathe immediately after birth, even a little?", blank=True, max_length=255)
    Id10112 = models.CharField("Did the baby have a breathing problem?", blank=True, max_length=255)
    Id10113 = models.CharField("Was the baby given assistance to breathe at birth?", blank=True, max_length=255)
    Id10114 = models.CharField("If the baby didn't show any sign of life, was it born dead?", blank=True, max_length=255)
    Id10115 = models.CharField("Were there any bruises or signs of injury on baby's body after the birth?", blank=True, max_length=255)
    Id10116 = models.CharField("Was the baby's body soft, pulpy and discoloured and the skin peeling away?", blank=True, max_length=255)
    Id10077 = models.CharField("Did (s)he suffer from any injury or accident that led to her/his death?", blank=True, max_length=255)
    Id10079 = models.CharField("Was it a road traffic accident?", blank=True, max_length=255)
    Id10080 = models.CharField("What was her/his role in the road traffic accident?", blank=True, max_length=255)
    Id10081 = models.CharField("What was the counterpart that was hit during the road traffic accident?", blank=True, max_length=255)
    Id10082 = models.CharField("Was (s)he injured in a non-road transport accident?", blank=True, max_length=255)
    Id10083 = models.CharField("Was (s)he injured in a fall?", blank=True, max_length=255)
    Id10084 = models.CharField("Was there any poisoning?", blank=True, max_length=255)
    Id10085 = models.CharField("Did (s)he die of drowning?", blank=True, max_length=255)
    Id10086 = models.CharField("Was (s)he injured by a bite or sting by venomous animal?", blank=True, max_length=255)
    Id10087 = models.CharField("Was (s)he injured by an animal or insect (non-venomous)?", blank=True, max_length=255)
    Id10088 = models.CharField("What was the animal/insect?", blank=True, max_length=255)
    Id10089 = models.CharField("Was (s)he injured by burns/fire?", blank=True, max_length=255)
    Id10090 = models.CharField("Was (s)he subject to violence (suicide, homicide, abuse)?", blank=True, max_length=255)
    Id10091 = models.CharField("Was (s)he injured by a firearm?", blank=True, max_length=255)
    Id10092 = models.CharField("Was (s)he stabbed, cut or pierced?", blank=True, max_length=255)
    Id10093 = models.CharField("Was (s)he strangled?", blank=True, max_length=255)
    Id10094 = models.CharField("Was (s)he injured by a blunt force?", blank=True, max_length=255)
    Id10095 = models.CharField("Was (s)he injured by a force of nature?", blank=True, max_length=255)
    Id10096 = models.CharField("Was it electrocution?", blank=True, max_length=255)
    Id10097 = models.CharField("Did (s)he encounter any other injury?", blank=True, max_length=255)
    Id10098 = models.CharField("Was the injury accidental?", blank=True, max_length=255)
    Id10099 = models.CharField("Was the injury self-inflicted?", blank=True, max_length=255)
    Id10100 = models.CharField("Was the injury intentionally inflicted by someone else?", blank=True, max_length=255)
    Id10351 = models.CharField("How many days old was the baby when the fatal illness started?", blank=True, max_length=255)
    Id10408 = models.CharField("Before the illness that led to death, was the baby/the child growing normally?", blank=True, max_length=255)
    Id10120_0 = models.CharField("For how many days was (s)he ill before death?", blank=True, max_length=255)
    id10120_unit = models.CharField("For how long was (s)he ill before death?", blank=True, max_length=255)
    Id10121 = models.CharField("Months", blank=True, max_length=255)
    Id10122 = models.CharField("Years", blank=True, max_length=255)
    Id10120_1 = models.CharField("Days", blank=True, max_length=255)
    Id10120 = models.CharField("Calculated Field: Calculated number of Days with illness", blank=True, max_length=255)
    Id10123 = models.CharField("Did (s)he die suddenly?", blank=True, max_length=255)
    Id10125 = models.CharField("Was there any diagnosis by a health professional of tuberculosis?", blank=True, max_length=255)
    Id10126 = models.CharField("Was an HIV test ever positive?", blank=True, max_length=255)
    Id10127 = models.CharField("Was there any diagnosis by a health professional of AIDS?", blank=True, max_length=255)
    Id10128 = models.CharField("Did (s)he have a recent positive test by a health professional for malaria?", blank=True, max_length=255)
    Id10129 = models.CharField("Did (s)he have a recent negative test by a health professional for malaria?", blank=True, max_length=255)
    Id10130 = models.CharField("Was there any diagnosis by a health professional of dengue fever?", blank=True, max_length=255)
    Id10131 = models.CharField("Was there any diagnosis by a health professional of measles?", blank=True, max_length=255)
    Id10132 = models.CharField("Was there any diagnosis by a health professional of high blood pressure?", blank=True, max_length=255)
    Id10133 = models.CharField("Was there any diagnosis by a health professional of heart disease?", blank=True, max_length=255)
    Id10134 = models.CharField("Was there any diagnosis by a health professional of diabetes?", blank=True, max_length=255)
    Id10135 = models.CharField("Was there any diagnosis by a health professional of asthma?", blank=True, max_length=255)
    Id10136 = models.CharField("Was there any diagnosis by a health professional of epilepsy?", blank=True, max_length=255)
    Id10137 = models.CharField("Was there any diagnosis by a health professional of cancer?", blank=True, max_length=255)
    Id10138 = models.CharField("Was there any diagnosis by a health professional of Chronic Obstructive Pulmonary Disease (COPD)?", blank=True, max_length=255)
    Id10139 = models.CharField("Was there any diagnosis by a health professional of dementia?", blank=True, max_length=255)
    Id10140 = models.CharField("Was there any diagnosis by a health professional of depression?", blank=True, max_length=255)
    Id10141 = models.CharField("Was there any diagnosis by a health professional of stroke?", blank=True, max_length=255)
    Id10142 = models.CharField("Was there any diagnosis by a health professional of sickle cell disease?", blank=True, max_length=255)
    Id10143 = models.CharField("Was there any diagnosis by a health professional of kidney disease?", blank=True, max_length=255)
    Id10144 = models.CharField("Was there any diagnosis by a health professional of liver disease?", blank=True, max_length=255)
    Id10147 = models.CharField("Did (s)he have a fever?", blank=True, max_length=255)
    Id10148_a = models.CharField("How many days did the fever last?", blank=True, max_length=255)
    Id10148_units = models.CharField("How long did the fever last?", blank=True, max_length=255)
    Id10148_b = models.CharField("Enter how long the fever lasted in days:", blank=True, max_length=255)
    Id10148_c = models.CharField("Enter how long the fever lasted in months:", blank=True, max_length=255)
    Id10148 = models.CharField("Calculated Field: How many days did the fever last?", blank=True, max_length=255)
    Id10149 = models.CharField("Did the fever continue until death?", blank=True, max_length=255)
    Id10150 = models.CharField("How severe was the fever?", blank=True, max_length=255)
    Id10151 = models.CharField("What was the pattern of the fever?", blank=True, max_length=255)
    Id10152 = models.CharField("Did (s)he have night sweats?", blank=True, max_length=255)
    Id10153 = models.CharField("Did (s)he have a cough?", blank=True, max_length=255)
    Id10154_units = models.CharField("For how long did (s)he have a cough?", blank=True, max_length=255)
    Id10154_a = models.CharField("Enter how long (s)he had a cough in days:", blank=True, max_length=255)
    Id10154_b = models.CharField("Enter how long (s)he had a cough in months:", blank=True, max_length=255)
    Id10154 = models.CharField("Calculated Field: For how many days did (s)he have a cough?", blank=True, max_length=255)
    Id10155 = models.CharField("Was the cough productive, with sputum?", blank=True, max_length=255)
    Id10156 = models.CharField("Was the cough very severe?", blank=True, max_length=255)
    Id10157 = models.CharField("Did (s)he cough up blood?", blank=True, max_length=255)
    Id10158 = models.CharField("Did (s)he make a whooping sound when coughing?", blank=True, max_length=255)
    Id10159 = models.CharField("Did (s)he have any difficulty breathing?", blank=True, max_length=255)
    Id10161_0 = models.CharField("For how many days did the difficulty breathing last?", blank=True, max_length=255)
    id10161_unit = models.CharField("For how long did the difficult breathing last?", blank=True, max_length=255)
    Id10161_1 = models.CharField("Enter how long the difficult breathing lasted in days:", blank=True, max_length=255)
    Id10162 = models.CharField("Enter how long the difficult breathing lasted in months:", blank=True, max_length=255)
    Id10163 = models.CharField("Enter how long the difficult breathing lasted in years:", blank=True, max_length=255)
    Id10161 = models.CharField("Calculated Field: Calculated number of Days with illness", blank=True, max_length=255)
    Id10165 = models.CharField("Was the difficulty continuous or on and off?", blank=True, max_length=255)
    Id10166 = models.CharField("During the illness that led to death, did (s)he have fast breathing?", blank=True, max_length=255)
    Id10167_a = models.CharField("For how many days did the fast breathing last?", blank=True, max_length=255)
    Id10167_units = models.CharField("How long did the fast breathing last?", blank=True, max_length=255)
    Id10167_b = models.CharField("Enter how long the fast breathing lasted in days:", blank=True, max_length=255)
    Id10167_c = models.CharField("Enter how long the fast breathing lasted in months:", blank=True, max_length=255)
    Id10167 = models.CharField("Calculated Field: How long did the fast breathing last?", blank=True, max_length=255)
    Id10168 = models.CharField("Did (s)he have breathlessness?", blank=True, max_length=255)
    Id10169_a = models.CharField("For how many days did (s)he have breathlessness?", blank=True, max_length=255)
    Id10169_units = models.CharField("How long did (s)he have breathlessness?", blank=True, max_length=255)
    Id10169_b = models.CharField("Enter how long (s)he had breathlessness in days:", blank=True, max_length=255)
    Id10169_c = models.CharField("Enter how long (s)he had breathlessness in months:", blank=True, max_length=255)
    Id10169 = models.CharField("Calculated Field: How long did (s)he have breathlessness?", blank=True, max_length=255)
    Id10170 = models.CharField("Was (s)he unable to carry out daily routines due to breathlessness?", blank=True, max_length=255)
    Id10171 = models.CharField("Was (s)he breathless while lying flat?", blank=True, max_length=255)
    Id10172 = models.CharField("Did you see the lower chest wall/ribs being pulled in as the child breathed in?", blank=True, max_length=255)
    Id10173_nc = models.CharField("During the illness that led to death did his/her breathing sound like any of the following:", blank=True, max_length=255)
    id10173_check = models.CharField("id10173_check", blank=True, max_length=255)
    Id10173_a = models.CharField("During the illness that led to death did (s)he have wheezing?", blank=True, max_length=255)
    Id10173 = models.CharField("Calculated Field: During the illness that led to death did his/her breathing sound like any of the following:", blank=True, max_length=255)
    Id10174 = models.CharField("Did (s)he have chest pain?", blank=True, max_length=255)
    Id10175 = models.CharField("Was the chest pain severe?", blank=True, max_length=255)
    Id10176 = models.CharField("How many days before death did (s)he have chest pain?", blank=True, max_length=255)
    Id10178_unit = models.CharField("How long did the chest pain last?", blank=True, max_length=255)
    Id10178 = models.CharField("Enter how long the chest pain lasted in minutes:", blank=True, max_length=255)
    Id10179 = models.CharField("Enter how long the chest pain lasted in hours:", blank=True, max_length=255)
    Id10179_1 = models.CharField("Enter how long the chest pain lasted in days:", blank=True, max_length=255)
    Id10181 = models.CharField("Did (s)he have more frequent loose or liquid stools than usual?", blank=True, max_length=255)
    Id10182_units = models.CharField("How long did (s)he have frequent loose or liquid stools?", blank=True, max_length=255)
    Id10182_a = models.CharField("Enter how long (s)he had frequent loose or liquid stools in days:", blank=True, max_length=255)
    Id10182_b = models.CharField("Enter how long (s)he had frequent loose or liquid stools in months:", blank=True, max_length=255)
    Id10182 = models.CharField("Calculated Field: For how many days did (s)he have frequent loose or liquid stools?", blank=True, max_length=255)
    Id10183 = models.CharField("How many stools did the baby or child have on the day that loose liquid stools were most frequent?", blank=True, max_length=255)
    Id10184_a = models.CharField("How many days before death did the frequent loose or liquid stools start?", blank=True, max_length=255)
    Id10184_units = models.CharField("How long before death did the frequent loose or liquid stools start?", blank=True, max_length=255)
    Id10184_b = models.CharField("Enter how long before death the frequent loose or liquid stools started in days:", blank=True, max_length=255)
    Id10184_c = models.CharField("Enter how long before death the frequent loose or liquid stools started in months:", blank=True, max_length=255)
    Id10185 = models.CharField("Did the frequent loose or liquid stools continue until death?", blank=True, max_length=255)
    Id10186 = models.CharField("At any time during the final illness was there blood in the stools?", blank=True, max_length=255)
    Id10187 = models.CharField("Was there blood in the stool up until death?", blank=True, max_length=255)
    Id10188 = models.CharField("Did (s)he vomit?", blank=True, max_length=255)
    Id10189 = models.CharField("To clarify: Did (s)he vomit in the week preceding the death?", blank=True, max_length=255)
    Id10190_units = models.CharField("How long before death did (s)he vomit?", blank=True, max_length=255)
    Id10190_a = models.CharField("Enter how long before death(s)he vomited in days:", blank=True, max_length=255)
    Id10190_b = models.CharField("Enter how long before death(s)he vomited in months:", blank=True, max_length=255)
    Id10191 = models.CharField("Was there blood in the vomit?", blank=True, max_length=255)
    Id10192 = models.CharField("Was the vomit black?", blank=True, max_length=255)
    Id10193 = models.CharField("Did (s)he have any belly (abdominal) problem?", blank=True, max_length=255)
    Id10194 = models.CharField("Did (s)he have belly (abdominal) pain?", blank=True, max_length=255)
    Id10195 = models.CharField("Was the belly (abdominal) pain severe?", blank=True, max_length=255)
    id10196_unit = models.CharField("For how long did (s)he have belly (abdominal) pain?", blank=True, max_length=255)
    Id10196 = models.CharField("Enter how long (s)he had belly (abdominal) pain in hours:", blank=True, max_length=255)
    Id10197_a = models.CharField("Enter how long (s)he had belly (abdominal) pain in days:", blank=True, max_length=255)
    Id10198 = models.CharField("Enter how long (s)he had belly (abdominal) pain in months:", blank=True, max_length=255)
    Id10197 = models.CharField("Calculated Field: Calculated number of Days with belly pain", blank=True, max_length=255)
    Id10199 = models.CharField("Was the pain in the upper or lower belly (abdomen)?", blank=True, max_length=255)
    Id10200 = models.CharField("Did (s)he have a more than usually protruding belly (abdomen)?", blank=True, max_length=255)
    Id10201_unit = models.CharField("For how long before death did (s)he have a more than usually protruding belly (abdomen)?", blank=True, max_length=255)
    Id10201_a = models.CharField("Enter how long before death (s)he had a more than usually protruding belly (abdomen) in days:", blank=True, max_length=255)
    Id10202 = models.CharField("Enter how long before death (s)he had a more than usually protruding belly (abdomen) in months:", blank=True, max_length=255)
    Id10201 = models.CharField("Calculated Field: Calculated number of Days with protruding belly (abdomen)", blank=True, max_length=255)
    Id10203 = models.CharField("How rapidly did (s)he develop the protruding belly (abdomen)?", blank=True, max_length=255)
    Id10204 = models.CharField("Did (s)he have any mass in the belly (abdomen)?", blank=True, max_length=255)
    Id10205_unit = models.CharField("For how long did (s)he have a mass in the belly (abdomen)?", blank=True, max_length=255)
    Id10205_a = models.CharField("Enter how long (s)he had a mass in the belly (abdomen) in days:", blank=True, max_length=255)
    Id10206 = models.CharField("Enter how long (s)he had a mass in the belly (abdomen) in months:", blank=True, max_length=255)
    Id10205 = models.CharField("Calculated Field: Calculated number of Days with a mass in the belly (abdomen)", blank=True, max_length=255)
    Id10207 = models.CharField("Did (s)he have a severe headache?", blank=True, max_length=255)
    Id10208 = models.CharField("Did (s)he have a stiff neck during illness that led to death?", blank=True, max_length=255)
    Id10209_units = models.CharField("How long before death did (s)he have stiff neck?", blank=True, max_length=255)
    Id10209_a = models.CharField("Enter how long before death did (s)he have stiff neck in days:", blank=True, max_length=255)
    Id10209_b = models.CharField("Enter how long before death did (s)he have stiff neck in months:", blank=True, max_length=255)
    Id10209 = models.CharField("Calculated Field: For how many days before death did (s)he have stiff neck?", blank=True, max_length=255)
    Id10210 = models.CharField("Did (s)he have a painful neck during the illness that led to death?", blank=True, max_length=255)
    Id10211_units = models.CharField("How long before death did (s)he have a painful neck?", blank=True, max_length=255)
    Id10211_a = models.CharField("Enter how long before death (s)he had a painful neck in days:", blank=True, max_length=255)
    Id10211_b = models.CharField("Enter how long before death (s)he had a painful neck in months:", blank=True, max_length=255)
    Id10211 = models.CharField("Calculated Field: For how many days before death did (s)he have a painful neck?", blank=True, max_length=255)
    Id10212 = models.CharField("Did (s)he have mental confusion?", blank=True, max_length=255)
    Id10213_units = models.CharField("How long did (s)he have mental confusion?", blank=True, max_length=255)
    Id10213_a = models.CharField("Enter how long (s)he had mental confusion in days:", blank=True, max_length=255)
    Id10213_b = models.CharField("Enter how long (s)he had mental confusion in months:", blank=True, max_length=255)
    Id10213 = models.CharField("Calculated Field: For how many months did (s)he have mental confusion?", blank=True, max_length=255)
    Id10214 = models.CharField("Was (s)he unconscious during the illness that¬†led¬†to death?", blank=True, max_length=255)
    Id10215 = models.CharField("Was (s)he unconscious for more than 24 hours before death?", blank=True, max_length=255)
    Id10216_units = models.CharField("How long before death did unconsciousness start?", blank=True, max_length=255)
    Id10216_a = models.CharField("Enter how long before death unconsciousness started in hours]?", blank=True, max_length=255)
    Id10216_b = models.CharField("Enter how long before death unconsciousness started in days]?", blank=True, max_length=255)
    Id10216 = models.CharField("Calculated Field: How many hours before death did unconsciousness start?", blank=True, max_length=255)
    Id10217 = models.CharField("Did the unconsciousness start suddenly, quickly (at least within a single day)?", blank=True, max_length=255)
    Id10218 = models.CharField("Did the unconsciousness continue until death?", blank=True, max_length=255)
    Id10219 = models.CharField("Did (s)he have convulsions?", blank=True, max_length=255)
    Id10220 = models.CharField("Did (s)he experience any generalized convulsions or fits during the illness that led to death?", blank=True, max_length=255)
    Id10221 = models.CharField("For how many minutes did the convulsions last?", blank=True, max_length=255)
    Id10222 = models.CharField("Did (s)he become unconscious immediately after the convulsion?", blank=True, max_length=255)
    Id10223 = models.CharField("Did (s)he have any urine problems?", blank=True, max_length=255)
    Id10225 = models.CharField("Did (s)he go to urinate more often than usual?", blank=True, max_length=255)
    Id10226 = models.CharField("During the final illness did (s)he ever pass blood in the urine?", blank=True, max_length=255)
    Id10224 = models.CharField("Did (s)he stop urinating?", blank=True, max_length=255)
    Id10227 = models.CharField("Did (s)he have sores or ulcers anywhere on the body?", blank=True, max_length=255)
    Id10228 = models.CharField("Did (s)he have sores?", blank=True, max_length=255)
    Id10229 = models.CharField("Did the sores have clear fluid or pus?", blank=True, max_length=255)
    Id10230 = models.CharField("Did (s)he have an ulcer (pit) on the foot?", blank=True, max_length=255)
    Id10231 = models.CharField("Did the ulcer on the foot ooze pus?", blank=True, max_length=255)
    Id10232_units = models.CharField("How long did the ulcer on the foot ooze pus?", blank=True, max_length=255)
    Id10232_a = models.CharField("Enter how long the ulcer on the foot oozed pus in days:", blank=True, max_length=255)
    Id10232_b = models.CharField("Enter how long the ulcer on the foot oozed pus in months:", blank=True, max_length=255)
    Id10232 = models.CharField("Calculated Field: For how many days did the ulcer on the foot ooze pus?", blank=True, max_length=255)
    Id10233 = models.CharField("During the illness that led to death, did (s)he have any skin rash?", blank=True, max_length=255)
    Id10234 = models.CharField("For how many days did (s)he have the skin rash?", blank=True, max_length=255)
    Id10235 = models.CharField("Where was the rash?", blank=True, max_length=255)
    id10235_check = models.CharField("It is not possible to select \"Doesn't Know\" or \"Refused to answer\" together with other options. Please go back and correct the selection.", blank=True, max_length=255)
    Id10236 = models.CharField("Did (s)he have measles rash (use local term)?", blank=True, max_length=255)
    Id10237 = models.CharField("Did (s)he ever have shingles or herpes zoster?", blank=True, max_length=255)
    Id10238 = models.CharField("During the illness that led to death, did her/his skin flake off in patches?", blank=True, max_length=255)
    Id10239 = models.CharField("During the illness that led to death, did he/she have areas of the skin that turned black?", blank=True, max_length=255)
    Id10240 = models.CharField("During the illness that led to death, did he/she have areas of the skin with redness and swelling?", blank=True, max_length=255)
    Id10241 = models.CharField("During the illness that led to death, did (s)he bleed from anywhere?", blank=True, max_length=255)
    Id10242 = models.CharField("Did (s)he bleed from the nose, mouth or anus?", blank=True, max_length=255)
    Id10243 = models.CharField("Did (s)he have noticeable weight loss?", blank=True, max_length=255)
    Id10244 = models.CharField("Was (s)he severely thin or wasted?", blank=True, max_length=255)
    Id10245 = models.CharField("During the illness that led to death, did s/he have a whitish rash inside the mouth or on the tongue?", blank=True, max_length=255)
    Id10246 = models.CharField("Did (s)he have stiffness of the whole body or was unable to open the mouth?", blank=True, max_length=255)
    Id10247 = models.CharField("Did (s)he have puffiness of the face?", blank=True, max_length=255)
    Id10248_units = models.CharField("How long did (s)he have puffiness of the face?", blank=True, max_length=255)
    Id10248_a = models.CharField("Enter how long (s)he had puffiness of the face in days:", blank=True, max_length=255)
    Id10248_b = models.CharField("Enter how long (s)he had puffiness of the face in months:", blank=True, max_length=255)
    Id10248 = models.CharField("Calculated Field: For how many days did (s)he have puffiness of the face?", blank=True, max_length=255)
    Id10249 = models.CharField("During the illness that led to death, did (s)he have swollen legs or feet?", blank=True, max_length=255)
    Id10250_units = models.CharField("How long did the swelling last?", blank=True, max_length=255)
    Id10250_a = models.CharField("Enter how long the swelling lasted in days:", blank=True, max_length=255)
    Id10250_b = models.CharField("Enter how long the swelling lasted in months:", blank=True, max_length=255)
    Id10250 = models.CharField("Calculated Field: How many days did the swelling last?", blank=True, max_length=255)
    Id10251 = models.CharField("Did (s)he have both feet swollen?", blank=True, max_length=255)
    Id10252 = models.CharField("Did (s)he have general puffiness all over his/her body?", blank=True, max_length=255)
    Id10253 = models.CharField("Did (s)he have any lumps?", blank=True, max_length=255)
    Id10254 = models.CharField("Did (s)he have any lumps or lesions in the mouth?", blank=True, max_length=255)
    Id10255 = models.CharField("Did (s)he have any lumps on the neck?", blank=True, max_length=255)
    Id10256 = models.CharField("Did (s)he have any lumps on the armpit?", blank=True, max_length=255)
    Id10257 = models.CharField("Did (s)he have any lumps on the groin?", blank=True, max_length=255)
    Id10258 = models.CharField("Was (s)he in any way paralysed?", blank=True, max_length=255)
    Id10259 = models.CharField("Did (s)he have paralysis of only one side of the body?", blank=True, max_length=255)
    Id10260 = models.CharField("Which were the limbs or body parts paralysed?", blank=True, max_length=255)
    id10260_check = models.CharField("It is not possible to select \"only one side paralysed\" and \"left and right side\" or \"whole body\" together. Please go back and correct the selection.", blank=True, max_length=255)
    id10260_check2 = models.CharField("It is not possible to select \"Doesn't Know\" or \"Refused to answer\" together with other options. Please go back and correct the selection.", blank=True, max_length=255)
    Id10261 = models.CharField("Did (s)he have difficulty swallowing?", blank=True, max_length=255)
    Id10262_units = models.CharField("For how long before death did (s)he have difficulty swallowing?", blank=True, max_length=255)
    Id10262_a = models.CharField("Enter how long before death (s)he had difficulty swallowing in days:", blank=True, max_length=255)
    Id10262_b = models.CharField("Enter how long before death (s)he had difficulty swallowing in months:", blank=True, max_length=255)
    Id10262 = models.CharField("Calculated Field: For how many days before death did (s)he have difficulty swallowing?", blank=True, max_length=255)
    Id10263 = models.CharField("Was the difficulty with swallowing with solids, liquids, or both?", blank=True, max_length=255)
    Id10264 = models.CharField("Did (s)he have pain upon swallowing?", blank=True, max_length=255)
    Id10265 = models.CharField("Did (s)he have yellow discoloration of the eyes?", blank=True, max_length=255)
    Id10266_units = models.CharField("For how long did (s)he have the yellow discoloration?", blank=True, max_length=255)
    Id10266_a = models.CharField("Enter how long (s)he had the yellow discoloration in days:", blank=True, max_length=255)
    Id10266_b = models.CharField("Enter how long (s)he had the yellow discoloration in months:", blank=True, max_length=255)
    Id10266 = models.CharField("Calculated Field: For how many days did (s)he have the yellow discoloration?", blank=True, max_length=255)
    Id10267 = models.CharField("Did her/his hair change in color to a reddish or yellowish color?", blank=True, max_length=255)
    Id10268 = models.CharField("Did (s)he look pale (thinning/lack of blood) or have pale palms, eyes or nail beds?", blank=True, max_length=255)
    Id10269 = models.CharField("Did (s)he have sunken eyes?", blank=True, max_length=255)
    Id10270 = models.CharField("Did (s)he drink a lot more water than usual?", blank=True, max_length=255)
    Id10271 = models.CharField("Was the baby able to suckle or bottle-feed within the first 24 hours after birth?", blank=True, max_length=255)
    Id10272 = models.CharField("Did the baby ever suckle in a normal way?", blank=True, max_length=255)
    Id10273 = models.CharField("Did the baby stop suckling?", blank=True, max_length=255)
    Id10274_a = models.CharField("How many days after birth did the baby stop suckling?", blank=True, max_length=255)
    Id10274_units = models.CharField("How long after birth did the baby stop suckling?", blank=True, max_length=255)
    Id10274_b = models.CharField("Enter how long after birth the baby stopped suckling in days:", blank=True, max_length=255)
    Id10274_c = models.CharField("Enter how long after birth the baby stopped suckling in months:", blank=True, max_length=255)
    Id10274 = models.CharField("Calculated Field: How many days after birth did the baby stop suckling?", blank=True, max_length=255)
    Id10275 = models.CharField("Did the baby have convulsions starting within the first 24 hours of life?", blank=True, max_length=255)
    Id10276 = models.CharField("Did the baby have convulsions starting more than 24 hours after birth?", blank=True, max_length=255)
    Id10277 = models.CharField("Did the baby's body become stiff, with the back arched backwards?", blank=True, max_length=255)
    Id10278 = models.CharField("During the illness that led to death, did the baby have a bulging or raised fontanelle?", blank=True, max_length=255)
    Id10279 = models.CharField("During the illness that led to death, did the baby have a sunken fontanelle?", blank=True, max_length=255)
    Id10281 = models.CharField("During the illness that led to death, did the baby become unresponsive or unconscious?", blank=True, max_length=255)
    Id10282 = models.CharField("Did the baby become unresponsive or unconscious soon after birth, within less than 24 hours?", blank=True, max_length=255)
    Id10283 = models.CharField("Did the baby become unresponsive or unconscious more than 24 hours after birth?", blank=True, max_length=255)
    Id10284 = models.CharField("During the illness that led to death, did the baby become cold to touch?", blank=True, max_length=255)
    Id10285 = models.CharField("How many days old was the baby when it started feeling cold to touch?", blank=True, max_length=255)
    Id10286 = models.CharField("During the illness that led to death, did the baby become lethargic after a period of normal activity?", blank=True, max_length=255)
    Id10287 = models.CharField("Did the baby have redness or pus drainage from the umbilical cord stump?", blank=True, max_length=255)
    Id10288 = models.CharField("During the illness that led to death, did the baby have skin ulcer(s) or pits?", blank=True, max_length=255)
    Id10289 = models.CharField("During the illness that led to death, did the baby have yellow skin, palms (hand) or soles (foot)?", blank=True, max_length=255)
    Id10290 = models.CharField("Did the baby or infant appear to be healthy and then just die suddenly?", blank=True, max_length=255)
    Id10294 = models.CharField("Did she have any swelling or lump in the breast?", blank=True, max_length=255)
    Id10295 = models.CharField("Did she have any ulcers (pits) in the breast?", blank=True, max_length=255)
    Id10296 = models.CharField("Did she ever have a period or menstruate?", blank=True, max_length=255)
    Id10297 = models.CharField("When she had her period, did she have vaginal bleeding in between menstrual periods?", blank=True, max_length=255)
    Id10298 = models.CharField("Was the bleeding excessive?", blank=True, max_length=255)
    Id10301 = models.CharField("Was there excessive vaginal bleeding in the week prior to death?", blank=True, max_length=255)
    Id10299 = models.CharField("Did her menstrual period stop naturally because of menopause or removal of uterus?", blank=True, max_length=255)
    Id10302 = models.CharField("At the time of death was her period overdue?", blank=True, max_length=255)
    Id10303 = models.CharField("For how many weeks had her period been overdue?", blank=True, max_length=255)
    Id10300 = models.CharField("Did she have vaginal bleeding after cessation of menstruation?", blank=True, max_length=255)
    Id10304 = models.CharField("Did she have a sharp pain in her belly (abdomen) shortly before death?", blank=True, max_length=255)
    Id10305 = models.CharField("Was she pregnant or in labour at the time of death?", blank=True, max_length=255)
    Id10306 = models.CharField("Did she die within 6 weeks of delivery, abortion or miscarriage?", blank=True, max_length=255)
    Id10307 = models.CharField("Did this woman die more than 6 weeks after being pregnant or delivering a baby?", blank=True, max_length=255)
    Id10308 = models.CharField("Was this a woman who died less than 1 year after being pregnant or delivering a baby?", blank=True, max_length=255)
    Id10309 = models.CharField("For how many months was she pregnant?", blank=True, max_length=255)
    Id10310 = models.CharField("Please confirm, when she died, she was NEITHER pregnant NOR had delivered, had an abortion, or miscarried within 12 months of when she died--is that right?", blank=True, max_length=255)
    Id10310_check = models.CharField("If the response is NO, DON'T KNOW, OR REFUSED, it indicates some uncertainty as to whether the cause of death could have been a maternal or pregnancy-related cause. Go back to the question \"Did she ever have a period or menstruate?\" and follow the process again. If it is confirmed that the death was related to pregnancy, proceed with the next question ‚ÄúDid she die during labour or delivery?‚Äù", blank=True, max_length=255)
    Id10312 = models.CharField("Did she die during labour or delivery?", blank=True, max_length=255)
    Id10313 = models.CharField("Did she die after delivering a baby?", blank=True, max_length=255)
    Id10314 = models.CharField("Did she die within 24 hours after delivery?", blank=True, max_length=255)
    Id10315_a = models.CharField("Did she die within 6 weeks of childbirth?", blank=True, max_length=255)
    Id10315 = models.CharField("Calculated Field: Did she die within 6 weeks of childbirth?", blank=True, max_length=255)
    Id10316 = models.CharField("Did she give birth to a live baby (within 6 weeks of her death)?", blank=True, max_length=255)
    Id10317 = models.CharField("Did she die during or after a multiple pregnancy?", blank=True, max_length=255)
    Id10318 = models.CharField("Was she breastfeeding the child in the days before death?", blank=True, max_length=255)
    Id10319 = models.CharField("How many births, including stillbirths, did she/the mother have before this baby?", blank=True, max_length=255)
    Id10320 = models.CharField("Had she had any previous Caesarean section?", blank=True, max_length=255)
    Id10321 = models.CharField("During pregnancy, did she suffer from high blood pressure?", blank=True, max_length=255)
    Id10322 = models.CharField("Did she have foul smelling vaginal discharge during pregnancy or after delivery?", blank=True, max_length=255)
    Id10323 = models.CharField("During the last 3 months of pregnancy, did she suffer from convulsions?", blank=True, max_length=255)
    Id10324 = models.CharField("During the last 3 months of pregnancy did she suffer from blurred vision?", blank=True, max_length=255)
    Id10325 = models.CharField("Did bleeding occur while she was pregnant?", blank=True, max_length=255)
    Id10326 = models.CharField("Was there vaginal bleeding during the first 6 months of pregnancy?", blank=True, max_length=255)
    Id10327 = models.CharField("Was there vaginal bleeding during the last 3 months of pregnancy but before labour started?", blank=True, max_length=255)
    Id10328 = models.CharField("Did she have excessive bleeding during labour or delivery?", blank=True, max_length=255)
    Id10329 = models.CharField("Did she have excessive bleeding after delivery or abortion?", blank=True, max_length=255)
    Id10330 = models.CharField("Was the placenta completely delivered?", blank=True, max_length=255)
    Id10331 = models.CharField("Did she deliver or try to deliver an abnormally positioned baby?", blank=True, max_length=255)
    Id10332 = models.CharField("For how many hours was she in labour?", blank=True, max_length=255)
    Id10333 = models.CharField("Did she attempt to terminate the pregnancy?", blank=True, max_length=255)
    Id10334 = models.CharField("Did she recently have a pregnancy that ended in an abortion (spontaneous or induced)?", blank=True, max_length=255)
    Id10335 = models.CharField("Did she die during an abortion?", blank=True, max_length=255)
    Id10336 = models.CharField("Did she die within 6 weeks of having an abortion?", blank=True, max_length=255)
    Id10337 = models.CharField("Where did she give birth / complete the miscarriage / have the abortion?", blank=True, max_length=255)
    Id10338 = models.CharField("Did she receive professional assistance during the delivery?", blank=True, max_length=255)
    Id10339 = models.CharField("Who delivered the baby / completed the miscarriage / performed the abortion?", blank=True, max_length=255)
    Id10342 = models.CharField("Was the delivery normal vaginal, without forceps or vacuum?", blank=True, max_length=255)
    Id10343 = models.CharField("Was the delivery vaginal, with forceps or vacuum?", blank=True, max_length=255)
    Id10344 = models.CharField("Was the delivery a Caesarean section?", blank=True, max_length=255)
    Id10347 = models.CharField("Was the baby born more than one month early?", blank=True, max_length=255)
    Id10340 = models.CharField("Did she have an operation to remove her uterus shortly before death?", blank=True, max_length=255)
    Id10352_units = models.CharField("How old was the child when the fatal illness started?", blank=True, max_length=255)
    Id10352_a = models.CharField("Enter how old the child was when the fatal illness started in months:", blank=True, max_length=255)
    Id10352_b = models.CharField("Enter how old the child was when the fatal illness started in years:", blank=True, max_length=255)
    Id10352 = models.CharField("Calculated Field: How many years old was the child when the fatal illness started?", blank=True, max_length=255)
    Id10354 = models.CharField("Was the child part of a multiple birth?", blank=True, max_length=255)
    Id10355 = models.CharField("Was the child the first, second, or later in the birth order?", blank=True, max_length=255)
    Id10356 = models.CharField("Is the mother still alive?", blank=True, max_length=255)
    Id10357 = models.CharField("Did the mother die before, during or after the delivery?", blank=True, max_length=255)
    Id10358_units = models.CharField("How long after the delivery did the mother die?", blank=True, max_length=255)
    Id10358 = models.CharField("How many months after the delivery did the mother die?", blank=True, max_length=255)
    Id10359 = models.CharField("How many days after the delivery did the mother die?", blank=True, max_length=255)
    Id10359_a = models.CharField("How many weeks after the delivery did the mother die?", blank=True, max_length=255)
    Id10360 = models.CharField("Where was the deceased born?", blank=True, max_length=255)
    Id10361 = models.CharField("Did you/the mother receive professional assistance during the delivery?", blank=True, max_length=255)
    Id10362 = models.CharField("At birth, was the baby of usual size?", blank=True, max_length=255)
    Id10363 = models.CharField("At birth, was the baby smaller than usual, (weighing under 2.5 kg)?", blank=True, max_length=255)
    Id10364 = models.CharField("At birth, was the baby very much smaller than usual, (weighing under 1 kg)?", blank=True, max_length=255)
    Id10365 = models.CharField("At birth, was the baby larger than usual, (weighing over 4.5 kg)?", blank=True, max_length=255)
    id1036X_check = models.CharField("It is not possible to select \"No usual size at Birth\", \"No weighing under 2.5 kg\" and \"No weighing over 4.5 kg\" together. Please go back and correct the selection.", blank=True, max_length=255)
    Id10366_unit = models.CharField("Id10366_unit", blank=True, max_length=255)
    Id10366_a = models.CharField("Id10366_a", blank=True, max_length=255)
    Id10366_b = models.CharField("Id10366_b", blank=True, max_length=255)
    Id10366 = models.CharField("What was the weight (in grammes) of the deceased at birth?", blank=True, max_length=255)
    Id10367 = models.CharField("How many months long was the pregnancy before the child was born?", blank=True, max_length=255)
    Id10368 = models.CharField("Were there any complications in the late part of the pregnancy (defined as the last 3 months, before labour)?", blank=True, max_length=255)
    Id10369 = models.CharField("Were there any complications during labour or delivery?", blank=True, max_length=255)
    Id10370 = models.CharField("Was any part of the baby physically abnormal at time of delivery? (for example: body part too large or too small, additional growth on body)?", blank=True, max_length=255)
    Id10371 = models.CharField("Did the baby/ child have a swelling or defect on the back at time of birth?", blank=True, max_length=255)
    Id10372 = models.CharField("Did the baby/ child have a very large head at time of birth?", blank=True, max_length=255)
    Id10373 = models.CharField("Did the baby/ child have a very small head at time of birth?", blank=True, max_length=255)
    Id10394 = models.CharField("How many births, including stillbirths, did the baby's mother have before this baby?", blank=True, max_length=255)
    Id10376 = models.CharField("Was the baby moving in the last few days before the birth?", blank=True, max_length=255)
    Id10377 = models.CharField("Did the baby stop moving in the womb before labour started?", blank=True, max_length=255)
    Id10379_unit = models.CharField("How long before labour did you/the mother last feel the baby move?", blank=True, max_length=255)
    Id10379 = models.CharField("Enter how long before labour did you/the mother last feel the baby move in days:", blank=True, max_length=255)
    Id10380 = models.CharField("Enter how long before labour did you/the mother last feel the baby move in hours:", blank=True, max_length=255)
    Id10382 = models.CharField("How many hours did labour and delivery take?", blank=True, max_length=255)
    Id10383 = models.CharField("Was the baby born 24 hours or more after the water broke?", blank=True, max_length=255)
    Id10384 = models.CharField("Was the liquor foul smelling?", blank=True, max_length=255)
    Id10385 = models.CharField("What was the colour of the liquor when the water broke?", blank=True, max_length=255)
    Id10387 = models.CharField("Was the delivery normal vaginal, without forceps or vacuum?", blank=True, max_length=255)
    Id10388 = models.CharField("Was the delivery vaginal, with forceps or vacuum?", blank=True, max_length=255)
    Id10389 = models.CharField("Was the delivery a Caesarean section?", blank=True, max_length=255)
    id10389_check = models.CharField("It is not possible to select \"No\" to all three previous questions. Please go back and review the answers.", blank=True, max_length=255)
    Id10391 = models.CharField("Did you/the mother receive any vaccinations since reaching adulthood including during this pregnancy?", blank=True, max_length=255)
    Id10392 = models.CharField("How many doses?", blank=True, max_length=255)
    Id10393 = models.CharField("Did you/the mother receive tetanus toxoid (TT) vaccine?", blank=True, max_length=255)
    Id10395 = models.CharField("During labour, did the baby's mother suffer from fever?", blank=True, max_length=255)
    Id10396 = models.CharField("During the last 3 months of pregnancy, labour or delivery, did you/the baby's mother suffer from high blood pressure?", blank=True, max_length=255)
    Id10397 = models.CharField("Did you/the baby's mother have diabetes mellitus?", blank=True, max_length=255)
    Id10398 = models.CharField("Did you/the baby's mother have foul smelling vaginal discharge during pregnancy or after delivery?", blank=True, max_length=255)
    Id10399 = models.CharField("During the last 3 months of pregnancy, labour or delivery, did you/the baby's mother suffer from convulsions?", blank=True, max_length=255)
    Id10400 = models.CharField("During the last 3 months of pregnancy did you/the baby's mother suffer from blurred vision?", blank=True, max_length=255)
    Id10401 = models.CharField("Did you/the baby's mother have severe anemia?", blank=True, max_length=255)
    Id10402 = models.CharField("Did you/the baby's mother have vaginal bleeding during the last 3 months of pregnancy but before labour started?", blank=True, max_length=255)
    Id10403 = models.CharField("Did the baby's bottom, feet, arm or hand come out of the vagina before its head?", blank=True, max_length=255)
    Id10404 = models.CharField("Was the umbilical cord wrapped more than once around the neck of the child at birth?", blank=True, max_length=255)
    Id10405 = models.CharField("Was the umbilical cord delivered first?", blank=True, max_length=255)
    Id10406 = models.CharField("Was the baby blue in colour at birth?", blank=True, max_length=255)
    Id10411 = models.CharField("Did (s)he drink alcohol?", blank=True, max_length=255)
    Id10412 = models.CharField("Did (s)he use tobacco?", blank=True, max_length=255)
    Id10413 = models.CharField("Did (s)he smoke tobacco (cigarette, cigar, pipe, etc.)?", blank=True, max_length=255)
    Id10414 = models.CharField("What kind of tobacco did (s)he use ?", blank=True, max_length=255)
    id10414_check = models.CharField("It is not possible to select cigarettes or pipe and \"no\" to \"Did (s)he smoke tobacco?\". Please go back and correct the selections.", blank=True, max_length=255)
    Id10415 = models.CharField("How many cigarettes did (s)he smoke daily?", blank=True, max_length=255)
    Id10416 = models.CharField("How many times did¬†(s)he use tobacco products each day?", blank=True, max_length=255)
    Id10418 = models.CharField("Did (s)he receive any treatment for the illness that led to death?", blank=True, max_length=255)
    Id10419 = models.CharField("Did (s)he receive oral rehydration salts?", blank=True, max_length=255)
    Id10420 = models.CharField("Did (s)he receive (or need) intravenous fluids (drip) treatment?", blank=True, max_length=255)
    Id10421 = models.CharField("Did (s)he receive (or need) a blood transfusion?", blank=True, max_length=255)
    Id10422 = models.CharField("Did (s)he receive (or need) treatment/food through a tube passed through the nose?", blank=True, max_length=255)
    Id10423 = models.CharField("Did (s)he receive (or need) injectable antibiotics?", blank=True, max_length=255)
    Id10424 = models.CharField("Did (s)he receive (or need) antiretroviral therapy (ART)?", blank=True, max_length=255)
    Id10425 = models.CharField("Did (s)he have (or need) an operation for the illness?", blank=True, max_length=255)
    Id10426 = models.CharField("Did (s)he have the operation within 1 month before death?", blank=True, max_length=255)
    Id10427 = models.CharField("Was (s)he discharged from hospital very ill?", blank=True, max_length=255)
    Id10428 = models.CharField("Did (s)he receive any immunizations?", blank=True, max_length=255)
    Id10429 = models.CharField("Do you have the child's vaccination card?", blank=True, max_length=255)
    Id10430 = models.CharField("Can I see the vaccination card (note the vaccines the child received)?", blank=True, max_length=255)
    Id10431 = models.CharField("Select EPI vaccines done", blank=True, max_length=255)
    id10431_check = models.CharField("It is not possible to select \"No vaccines\", \"Don't know\" or \"refuse\" together with other options. Please go back and correct the selection.", blank=True, max_length=255)
    Id10432 = models.CharField("Was care sought outside the home while (s)he had this illness?", blank=True, max_length=255)
    Id10433 = models.CharField("Where or from whom did you seek care?", blank=True, max_length=255)
    id10433_check = models.CharField("It is not possible to select \"Don't know\" or \"refuse\" together with other options. Please go back and correct the selection.", blank=True, max_length=255)
    Id10434 = models.CharField("What was the name and address of any hospital, health center or clinic where care was sought", blank=True, max_length=255)
    Id10435 = models.CharField("Did a health care worker tell you the cause of death?", blank=True, max_length=255)
    Id10436 = models.CharField("What did the health care worker say?", blank=True, max_length=255)
    Id10437 = models.CharField("Do you have any health records that belonged to the deceased?", blank=True, max_length=255)
    Id10438 = models.CharField("Can I see the health records?", blank=True, max_length=255)
    Id10439_check = models.CharField("Is the date of the most recent (last) visit available?", blank=True, max_length=255)
    Id10439 = models.CharField("Record the date of the most recent (last) visit", blank=True, max_length=255)
    Id10440_check = models.CharField("Is the date of the second most recent visit available?", blank=True, max_length=255)
    Id10440 = models.CharField("Record the date of the second most recent visit", blank=True, max_length=255)
    Id10441_check = models.CharField("Is the date of the last note on the health records available?", blank=True, max_length=255)
    Id10441 = models.CharField("Record the date of the last note on the health records", blank=True, max_length=255)
    Id10442 = models.CharField("Record the weight (in kilogrammes) written at the most recent (last) visit", blank=True, max_length=255)
    Id10443 = models.CharField("Record the weight (in kilogrammes) written at the second most recent visit", blank=True, max_length=255)
    Id10444 = models.CharField("Transcribe the last note on the health records", blank=True, max_length=255)
    Id10445 = models.CharField("Has the deceased's (biological) mother ever been tested for HIV?", blank=True, max_length=255)
    Id10446 = models.CharField("Has the deceased's (biological) mother ever been told she had HIV/AIDS by a health worker?", blank=True, max_length=255)
    Id10450 = models.CharField("In the final days before death, did s/he travel to a hospital or health facility?", blank=True, max_length=255)
    Id10451 = models.CharField("Did (s)he use motorised transport to get to the hospital or health facility?", blank=True, max_length=255)
    Id10452 = models.CharField("Were there any problems during admission to the hospital or health facility?", blank=True, max_length=255)
    Id10453 = models.CharField("Were there any problems with the way (s)he was treated (medical treatment, procedures, interpersonal attitudes, respect, dignity) in the hospital or health facility?", blank=True, max_length=255)
    Id10454 = models.CharField("Were there any problems getting medications or diagnostic tests in the hospital or health facility?", blank=True, max_length=255)
    Id10455 = models.CharField("Does it take more than 2 hours to get to the nearest hospital or health facility from the deceased's household?", blank=True, max_length=255)
    Id10456 = models.CharField("In the final days before death, were there any doubts about whether medical care was needed?", blank=True, max_length=255)
    Id10457 = models.CharField("In the final days before death, was traditional medicine used?", blank=True, max_length=255)
    Id10458 = models.CharField("In the final days before death, did anyone use a telephone or cell phone to call for help?", blank=True, max_length=255)
    Id10459 = models.CharField("Over the course of illness, did the total costs of care and treatment prohibit other household payments?", blank=True, max_length=255)
    Id10462 = models.CharField("Was a medical certificate of cause of death issued?", blank=True, max_length=255)
    Id10463 = models.CharField("Can I see the medical certificate of cause of death?", blank=True, max_length=255)
    Id10464 = models.CharField("Record the immediate cause of death from the certificate (line 1a)", blank=True, max_length=255)
    Id10465 = models.CharField("Duration (Ia):", blank=True, max_length=255)
    Id10466 = models.CharField("Record the first antecedent cause of death from the certificate (line 1b)", blank=True, max_length=255)
    Id10467 = models.CharField("Duration (Ib):", blank=True, max_length=255)
    Id10468 = models.CharField("Record the second antecedent cause of death from the certificate (line 1c)", blank=True, max_length=255)
    Id10469 = models.CharField("Duration (Ic):", blank=True, max_length=255)
    Id10470 = models.CharField("Record the third antecedent cause of death from the certificate (line 1d)", blank=True, max_length=255)
    Id10471 = models.CharField("Duration (Id):", blank=True, max_length=255)
    Id10472 = models.CharField("Record the contributing cause(s) of death from the certificate (part 2)", blank=True, max_length=255)
    Id10473 = models.CharField("Duration (part2):", blank=True, max_length=255)
    Id10481 = models.CharField("Id10481", blank=True, max_length=255)
    geopoint = models.CharField("geopoint", blank=True, max_length=255)
    comment = models.TextField("Comment", blank=True)
    # Track the history of changes to each verbal autopsy
    history = HistoricalRecords()
    # Automatically set timestamps
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # function to tell if VA had any coding errors
    def any_errors(self):
        return self.coding_issues.filter(severity='error').exists()

    # function to tell if VA had any coding warnings
    def any_warnings(self):
        return self.coding_issues.filter(severity='warning').exists()


class CauseOfDeath(models.Model):
    # One VerbalAutopsy can have multiple causes of death (through different algorithms)
    verbalautopsy = models.ForeignKey(VerbalAutopsy, related_name='causes', on_delete=models.CASCADE)
    # Track the cause and the algorithm that provided the cause
    cause = models.TextField()
    # TODO: do we want the algorithm as a string or by referring to an algorithm table?
    algorithm = models.TextField()
    # Store the settings used for this particular coding run
    # NOTE: by using JSONField we tie ourselves to postgres
    settings = JSONField()
    # Track the history of changes to each verbal autopsy cause of death coding
    # TODO: confirm that we need a history of this
    history = HistoricalRecords()
    # Automatically set timestamps
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.cause

class CauseCodingIssue(models.Model):
    # One VerbalAutopsy can have multiple coding issues
    verbalautopsy = models.ForeignKey(VerbalAutopsy, related_name='coding_issues', on_delete=models.CASCADE)
    text = models.TextField()
    SEVERITY_OPTIONS = ['error', 'warning']
    severity = models.CharField(max_length=7, choices=[(option, option) for option in SEVERITY_OPTIONS])
    # We track which algorithm and the settings for that algorithm
    # NOTE: this is a denormalized approach for convenience, which should still scale reasonably
    algorithm = models.TextField()
    # NOTE: by using JSONField we tie ourselves to postgres
    settings = JSONField()
    # Automatically set timestamps
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text
