#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE=config.settings.production

echo "Running database migrations..."
python /app/manage.py migrate

echo "Starting gunicorn..."
/usr/local/bin/gunicorn config.wsgi --bind=0.0.0.0:5000 --chdir=/app --workers=4 --threads=4
