#!/bin/bash

set -o errexit
set -o nounset

export DJANGO_SETTINGS_MODULE=config.settings.production

celery -A config.celery_app.app flower --url-prefix="/celery" --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}" -l INFO
