#!/bin/bash

set -o errexit
set -o nounset

export DJANGO_SETTINGS_MODULE=config.settings.production

celery flower \
    --app=config.celery_app.app \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
