# Generated by Django 3.1.5 on 2022-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataCleanup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("download", "Can download"),
                    ("bulk_download", "Can bulk download"),
                ),
                "managed": False,
                "default_permissions": ("view",),
            },
        ),
    ]
