# Generated by Django 3.1.5 on 2021-01-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210122_1422"),
        ("users", "0003_auto_20210119_1624"),
    ]

    operations = []
