# Generated by Django 3.1.5 on 2021-02-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20210127_1700"),
        ("users", "0004_userpasswordhistory"),
    ]

    operations = []
