# Generated by Django 3.1.5 on 2021-06-01 18:18

from django.db import migrations
import uuid

# add unique uuid values for each user in db
def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("users", "user")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_user_uuid"),
    ]

    operations = [migrations.RunPython(gen_uuid)]
