name: Documentation

# Only run workflow on pull requests that target /docs
on:
  push:
  pull_request:
   paths:
     - docs

# Separate build and deploy so that deploys don't happen on failed builds
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3           # Get code
      - uses: actions/setup-python@v4       # Get Python for dependencies
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/docs.txt
          cd docs

      - name: Build ePub
        run: |
          make epub
      - uses: actions/upload-artifact@v3
        with:
          name: docs-epub
          path: docs/_build/epub/*.epub     # Allow generic name of epub

      - name: Build pdf
        run: |
          make latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "docs/_build/latex/*.tex"
          glob_root_file: true
        uses: actions/upload-artifact@v3
        with:
          name: docs-pdf
          path: docs/_build/latex/*.pdf     # Allow generic name of pdf

      - name: Build html
        run: |
          make html
      - uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3           # Get code
      - uses: actions/download-artifact@v3  # Get html we're deploying
        with:
          name: docs-html
          path: docs/_build/html

      - uses: actions/download-artifact@v3  # Get offline artifacts
        with:
          name: docs-epub
          path: docs/_build/html/_static/VAExplorerDocs.epub
      - uses: actions/download-artifact@v3
        with:
          name: docs-pdf
          path: docs/_build/html/_static/VAExplorerDocs.pdf

      - uses: peaceiris/actions-gh-pages@v3   # Deploy to github pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html
