# Generated by Django 3.0.8 on 2020-07-30 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verbal_autopsy', '0002_causecodingissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='users',
            field=models.ManyToManyField(related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
