# Generated by Django 3.0.8 on 2020-08-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbal_autopsy', '0003_location_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='users',
        ),
    ]
